<?php

/**
 * @file
 * Functions to support theming in the Aardvarck theme.
 */

use Drupal\Core\Url;

/**
 * Implements hook_preprocess_page().
 */
function aardvarck_preprocess_page(&$variables): void {
  // Page title.
  $variables['page_title'] = \Drupal::service('title_resolver')
    ->getTitle(\Drupal::request(), \Drupal::routeMatch()->getRouteObject());
  // Node page.
  $variables['is_node'] = \Drupal::routeMatch()->getParameter('node') instanceof \Drupal\node\NodeInterface;
  // Taxonomy term page.
  $variables['is_taxonomy_term'] = \Drupal::routeMatch()->getParameter('taxonomy_term') instanceof \Drupal\taxonomy\TermInterface;
  // User page.
  $variables['is_user'] = \Drupal::routeMatch()->getParameter('user') instanceof \Drupal\user\UserInterface;
}

/**
 * Implements hook_preprocess_breadcrumb().
 */
function aardvarck_preprocess_breadcrumb(&$variables): void {
  $current_request = \Drupal::request();
  $current_path = $current_request->getPathInfo();
  $current_url = Url::fromUserInput($current_path)->toString();

  $route_match = \Drupal::routeMatch();
  $node = $route_match->getParameter('node');

  // Add current page to breadcrumb.
  if ($node && method_exists($node, 'getTitle')) {
    $current_title = $node->getTitle();
  } else {
    $current_title = \Drupal::service('title_resolver')
      ->getTitle($current_request, $route_match->getRouteObject());
  }

  if (!empty($variables['breadcrumb'])) {
    $variables['breadcrumb'][] = [
      'text' => $current_title,
      'url' => $current_url,
    ];
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function aardvarck_preprocess_menu(&$variables): void {
  $menu = \Drupal::entityTypeManager()
    ->getStorage('menu')
    ->load($variables['menu_name']);
  $variables['menu_aria_label'] = $menu->label() . ' menu';
}
